project_path: .
model_path: models/sequifier-default-best-100.onnx
data_path: data/daily-min-temperatures-split2.parquet

ddconfig_path: configs/ddconfigs/daily-min-temperatures.json

selected_columns: [Temp] # should include all target column, can include additional columns
target_columns: [Temp]
target_column_types: # 'criterion' in training_spec must also be adapted
  Temp: real

output_probabilities: false
map_to_id: false
device: cpu
seq_length: 50
inference_batch_size: 10

autoregression: false