project_path: .
data_path: data/daily-min-temperatures.csv
read_format: csv
write_format: parquet
selected_columns: [Temp] # should include all target column, can include additional columns
target_columns: [Temp]
return_targets: true

group_proportions:
- 0.8
- 0.1
- 0.1
seq_length: 100
max_rows: null