project_path: .
model_name: default
read_format: parquet
ddconfig_path: configs/ddconfigs/daily-min-temperatures.json

selected_columns: [Temp] # should include all target column, can include additional columns
target_columns: [Temp]
target_column_types: # 'criterion' in training_spec must also be adapted
  Temp: real

seq_length: 50
inference_batch_size: 10

export_onnx: true

model_spec:
  d_model: 250
  nhead: 10
  d_hid: 250
  nlayers: 2
training_spec:
  device: cpu
  epochs: 100
  iter_save: 5
  batch_size: 100
  log_interval: 10
  lr: 0.001
  accumulation_steps: 1
  dropout: 0.1
  criterion:
    Temp: MSELoss
  optimizer:
    name: AdamW
  scheduler:
    name: CosineAnnealingLR
    T_max: 100
    eta_min: 0.0001
  continue_training: false